<?php
/**
*/
$orders = $block->getOrders();
$columns = $block->getColumns();
$lastItemNumber = count($columns);
$_showhead = true;
$guestDesign = $block->getProductGuestDesign();
?>
<div class="block account-nav">
	<!--div class="title">
		<strong><?php /* @escapeNotVerified */ //echo __('My Customized Products'); ?></strong>
	</div-->
	<div class="table-wrapper my-customized-design">
		<table class="data table table-product-item">
			<caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Customized Products') ?></caption>
			<?php
				foreach($orders as $_or_key => $_order) {
					$orId = $_order->getEntityId();
					$status = $_order->getStatus();
					$j = 0;
					$items = $_order->getItemsCollection();
					foreach($items as $_item) {
						//class $_item is Magento\Sales\Model\Order\Item
						if ($_item->getParentItem() || $_item->getProductType() != 'pdpro') {
							continue;
						} else {
							$j++;
						}
					?>
					<?php if($j && $_showhead) { 
						$_showhead = false; ?>
						<thead>
							<tr>
								<?php $i = 0;
								foreach ($columns as $columnName => $columnTitle):?>
									<?php $i++; ?>
									<th <?php if($columnName == 'status') echo 'align="right"'; ?> class="col-<?php /* @noEscape */ echo $columnName ?><?php /* @noEscape */ echo ($i === $lastItemNumber ? ' last' : '')?>"><span><?php /* @noEscape */ echo __($columnTitle) ?></span></th>
								<?php endforeach; ?>					
							</tr>
						</thead>					
					<?php } ?>
					<tbody class="<?php /* @noEscape */ echo $j%2 ? 'even' : 'odd' ?>">
						<?php echo $block->getItemHtml($_item, $status) ?>
					</tbody>
					<?php
					}
				}
			?>
			<?php 
				$_j = 0;
				foreach($guestDesign as $guestItem) {
					if(isset($guestItem['product_id']) && isset($guestItem['design_id']) && isset($guestItem['pdp_product_id'])) {
						$_j++;
						$_product = $block->getProductWithId($guestItem['product_id']);
						$_design = $block->getDesignWithId($guestItem['design_id']);
					}
					if($_j && $_showhead) {
						$_showhead = false;
					?>
						<thead>
							<tr>
								<?php $_i = 0;
								foreach ($columns as $columnName => $columnTitle):?>
									<?php $_i++; ?>
									<th <?php if($columnName == 'status') echo 'align="right"'; ?> class="col-<?php /* @noEscape */ echo $columnName ?><?php /* @noEscape */ echo ($_i === $lastItemNumber ? ' last' : '')?>"><span><?php /* @noEscape */ echo __($columnTitle) ?></span></th>
								<?php endforeach; ?>					
							</tr>
						</thead>						
					<?php
						}
						if($_j) {
					?>
					<tbody class="<?php /* @noEscape */ echo $_j%2 ? 'even' : 'odd' ?>">
						<tr>
							<td class="col-product">
								<div class="product-detail">
									<div class="product-image">
										<img width="207" src="<?php echo $block->getImageProduct($_product)?>" alt="" />
									</div>
									<div class="block-info" style="float:left;">
										<ul class="items">
											<li><?php /* @noEscape */ echo $_product->getName() ?></li>
											<li><?php /* @noEscape */ echo __('SKU: ') ?><?php /* @noEscape */ echo $_product->getSku() ?></li>
										</ul>
									</div>
								</div>
							</td>
							<td class="col-custom-design">
								<ul class="items">
									<?php
										$_i = 0;
										foreach($_design as $sideThub) {
											if($sideThub['thumb']) {	
											$_last = $_i%2==0?'last':'';
									?>
											<li class="item <?php echo $_last ?>"><a href="<?php echo $block->getUrlToolDesign().'/'.$sideThub['thumb'] ?>" target="_blank"><img style="border:1px solid #C1C1C1;" width="143" src="<?php echo $block->getUrlToolDesign().'/'.$sideThub['thumb'] ?>" alt="" /></li>
									<?php 
											} 
										} 
									?>
								</ul>
							</td>
							<td class="col-price">
								<span class="box-price">
									<span class="item-price"><?php /* @noEscape */ echo $block->getPriceHtml($_product) ?></span>
								</span>
							</td>
							<td align="right" class="col-status last">
								<span class="item-status"><?php /* @noEscape */ echo __('Pending') ?></span>
								<div class="block-button">
									<?php /*<a class="zip-design" href="javascript:void(0)" data-href="<?php echo $block->getLinkZipDesign($guestItem['design_id']) ?>"><?php echo __('Zip Design') ?></a>*/?>
									<a class="edit-button" href="<?php echo $block->getLinkEdit($guestItem['design_id'], $guestItem['pdp_product_id']) ?>"> <?php echo __('Edit Design') ?></a>
								</div>
							</td>
						</tr>
					</tbody>
					<?php
						}
				}
			?>
		</table>
	</div>
</div>
<script>
require([
    'jquery',
    'Magento_Ui/js/modal/alert',
    'Magento_Ui/js/modal/confirm',
    'mage/translate'
], function($, alert, confirmation, $t){
	var alertModal = function(title, message) {
			alert({
				title: $.mage.__("!"+title),
				content: $.mage.__(message),
				autoOpen: true,
				clickableOverlay: false,
				focus: "",
				actions: {
					always: function(){
					}
				}
			});
	};
	var confirmModal = function (title, msg,onOkay,onCancel)
  {
    var emptyFunc = function (){ };
    this.title = title | 'Confirmation Question Dialog';
    this.msg = msg;
    this.onOkay = typeof onOkay === 'function' ? onOkay : emptyFunc;
    this.onCancel = typeof onCancel === 'function' ? onCancel : emptyFunc;
    this.modal = confirmation({
                                title: this.title,
                                content: this.msg,
                                actions: {
                                  confirm: this.onOkay,
                                  cancel: this.onCancel,
                                  always: emptyFunc
                                },
                                autoOpen : true,
                                clickableOverlay : false
                              });
    return this;
  };
    $(document).ready(function() {
        $('.block-button a.zip-design').each(function(){
			$(this).click(function(){
				var url = $(this).data('href');
        var reload = $(this).data('editor-uri');
        var returnUri = window.location.href;
        reload += '&return-uri=' + encodeURIComponent(returnUri);
        if(url != '#') {
					$.ajax({
						url: url,
						type: 'GET',
						beforeSend: function() {                  
							$('body').trigger('processStart');                 
						},
						success : function(_res) {
              $('body').trigger('processStop');
              if(typeof _res === 'object') {
                var res = _res;
              } else {
                res = $.parseJSON(_res);
              }
							if(res.status === 'success') {
								var data = res.data;
                window.location.href = data.baseUrl + '' + data.file;
							} else {
                if(res.message)
                {
                  var msg = res.message;
                }else{
                  msg = 'Cant zip design , the source SVG file missing.';
                }
                if(res.errorCode && res.errorCode === 15)
                {
                  msg += '<br /><strong>We need create it again from Design Editor . Press "<span style="color: #0fa7ff">OK</span>" then just wait , all done automatically !.</strong>';
                  confirmModal('Error',$t(msg),
                               function ()
                               {
                                 window.location.href = reload;
                               });
                }else{
                  alertModal('Error', $t(msg));
                }
//								alertModal('Error', 'can\'t zip design');
							}
						},
						error: function(xhr, ajaxOptions, thrownError){
							$('body').trigger('processStop');
//							alertModal('Error', thrownError);
              if(xhr.responseJSON && xhr.responseJSON.message)
              {
                var msg = xhr.responseJSON.message;
              }else{
                msg = '<?php echo __('Cant zip design , the source SVG file missing.') ?>';
              }
              if(xhr.responseJSON && xhr.responseJSON.errorCode && xhr.responseJSON.errorCode === 15)
              {
                msg += '<?php echo __('<br /><strong>We need create it again from Design Editor . Press "<span style="color: #0fa7ff">OK</span>" then just wait , all done automatically !.</strong>'); ?>';
                confirmModal('Error',msg,
                             function ()
                             {
                               window.location.href = reload;
                             });
              }else{
                alertModal('Error', msg);
              }
						}
					});					
				} else {
					alertModal('Error', 'can\'t zip design');
				}
			});
		});
    });	
});
</script>